export default [
  {
    id: 1,
    title: 'Basics',
    topics: [
      { id: 1.1, title: 'Html Basic Tags' },
      { id: 1.2, title: 'CSS Basic properties' },
      { id: 1.3, title: 'One page site demo' },
    ],
  },
  {
    id: 2,
    title: 'Box Modal',
    topics: [
      { id: 2.1, title: 'Box Modal' },
      { id: 2.2, title: 'Box Sizing' },
      { id: 2.3, title: 'Display (Inline & Block)' },
      { id: 2.4, title: 'CSS Selector' },
    ],
  },
  {
    id: 3,
    title: 'Positions',
    topics: [
      { id: 3.1, title: 'Css positions' },
      { id: 3.2, title: 'Z-index' },
      { id: 3.3, title: 'Overflow' },
    ],
  },
  {
    id: 4,
    title: 'Background',
    topics: [
      { id: 4.1, title: 'Background Size' },
      { id: 4.2, title: 'Background Position' },
      { id: 4.3, title: 'Origin, Clip, and Attachment' },
      { id: 4.4, title: 'Filters' },
      { id: 4.5, title: 'Styling SVGs' },
    ],
  },
  {
    id: 5,
    title: 'Units',
    topics: [
      { id: 5.1, title: 'Percentage' },
      { id: 5.2, title: 'Minimum Height and Maximum Width' },
      { id: 5.3, title: 'rem and em' },
      { id: 5.4, title: 'VH and VW' },
      { id: 5.5, title: 'Auto' },
    ],
  },
  {
    id: 6,
    title: 'Responsive',
    topics: [
      { id: 6.1, title: 'Media Query' },
      { id: 6.2, title: 'Viewport Meta Tag' },
      { id: 6.3, title: 'Mobile First' },
      { id: 6.4, title: 'Fluid Design' },
      { id: 6.5, title: 'Adaptive Design' },
    ],
  },
  {
    id: 7,
    title: 'Text and Fonts',
    topics: [
      { id: 7.1, title: 'Font Family' },
      { id: 7.2, title: 'Google Fonts' },
      { id: 7.3, title: 'Custom Fonts' },
      { id: 7.4, title: 'Font Format and Properties' },
      { id: 7.5, title: 'Letter Spacing' },
      { id: 7.6, title: 'Line Height' },
      { id: 7.7, title: 'Text Decoration and Shadow' },
    ],
  },
  {
    id: 8,
    title: 'Display Flex',
    topics: [
      { id: 8.1, title: 'What is Flexbox?' },
      { id: 8.2, title: 'Flex Container' },
      { id: 8.3, title: 'Flex Items' },
      { id: 8.4, title: 'Flex Direction' },
      { id: 8.5, title: 'Justify Content' },
      { id: 8.6, title: 'Align Items' },
      { id: 8.7, title: 'Flex Wrap' },
    ],
  },
  {
    id: 9,
    title: 'Display Grid',
    topics: [
      { id: 9.1, title: 'What is CSS Grid?' },
      { id: 9.2, title: 'Grid Container' },
      { id: 9.3, title: 'Grid Items' },
      { id: 9.4, title: 'Grid Template Columns and Rows' },
      { id: 9.5, title: 'Grid Area' },
      { id: 9.6, title: 'Justify and Align Items' },
      { id: 9.7, title: 'Grid Gap' },
    ],
  },
  {
    id: 10,
    title: 'Transforming Elements',
    topics: [
      { id: 10.1, title: 'Transform Origin' },
      { id: 10.2, title: 'Rotate and Translate' },
      { id: 10.3, title: 'Skew and Scale' },
      { id: 10.4, title: 'Transformation Shortcuts' },
      { id: 10.5, title: 'Rotation in 3D' },
      { id: 10.6, title: 'Translate Z' },
      { id: 10.7, title: 'Scaling Elements and Back Face Visibility' },
    ],
  },
];
