name: React CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test -- --coverage

      # Build the app for production
      - name: Build production app
        run: npm run build

  deploy:
    runs-on: ubuntu-latest

    needs: build
    environment: production # Ya staging, depending on aap kis environment me deploy kar rahe ho

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key for deployment
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H your-server.com >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh username@your-server.com 'cd /path/to/your/project && git pull && npm install && pm2 restart your-app'
